// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBaYABLW81e_rd6T1BUIB3JyxUYs7oj_Y',
    appId: '1:822468016493:web:956d11854e8a5878b2c264',
    messagingSenderId: '822468016493',
    projectId: 'nadacity-f34e9',
    authDomain: 'nadacity-f34e9.firebaseapp.com',
    storageBucket: 'nadacity-f34e9.firebasestorage.app',
    measurementId: 'G-WNN4BVHCFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLgnPjiGBnxL3ZZHHzZ3z7HbLAJr_IO2Q',
    appId: '1:822468016493:android:2214d8cefb41a0bbb2c264',
    messagingSenderId: '822468016493',
    projectId: 'nadacity-f34e9',
    storageBucket: 'nadacity-f34e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoD03FDDGk_2VZ6ikshyuV6CaqXDhaWNw',
    appId: '1:822468016493:ios:f48b60cdf0b81113b2c264',
    messagingSenderId: '822468016493',
    projectId: 'nadacity-f34e9',
    storageBucket: 'nadacity-f34e9.firebasestorage.app',
    iosBundleId: 'com.example.reelstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoD03FDDGk_2VZ6ikshyuV6CaqXDhaWNw',
    appId: '1:822468016493:ios:f48b60cdf0b81113b2c264',
    messagingSenderId: '822468016493',
    projectId: 'nadacity-f34e9',
    storageBucket: 'nadacity-f34e9.firebasestorage.app',
    iosBundleId: 'com.example.reelstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBaYABLW81e_rd6T1BUIB3JyxUYs7oj_Y',
    appId: '1:822468016493:web:3e0f26f327da92b7b2c264',
    messagingSenderId: '822468016493',
    projectId: 'nadacity-f34e9',
    authDomain: 'nadacity-f34e9.firebaseapp.com',
    storageBucket: 'nadacity-f34e9.firebasestorage.app',
    measurementId: 'G-YMRFRTFGFS',
  );
}
